### ISSUE TITLE
bbox info

### ISSUE THREAD

**Issue by Yashi-Nan** [deepwise-code/DLIA#1]
Hi, I wonder what are those numbers stand for in lesion_bbox.txt?

**Comment by tangtongxiao** [comment]
I think this is the range of the positive sample (ie blood vessel)
















At 2021-03-30 11:39:13, "Yashi-Nan" ***@***.***> wrote:

Hi, I wonder what are those numbers stand for in lesion_bbox.txt?

**Comment by Yashi-Nan** [comment]
Thanks very much for your reply @tangtongxiao 

I noticed that there are 7 numbers in the 'lesion_bbox.txt' provided ('1005642077 7 245 292 10 14 12'), and what exactly do they represent? especially the first number, is it used somewhere?

**Comment by deepwise-code** [comment]
one row info in "lesion_bbox.txt" file, these fileds mean:
0: patient id of  positive anenurysm case, witch also can be found in train dataset
1-6: lesion bbox info with order zxydwh of lesion *n* in case;
if a positive case has more than one aneurysm lesion, then the content of  "lesion_bbox.txt" will contain multi rows lesion records corresponding

**Comment by Yashi-Nan** [comment]
> one row info in "lesion_bbox.txt" file, these fileds mean:
> 0: patient id of positive anenurysm case, witch also can be found in train dataset
> 1-6: lesion bbox info with order zxydwh of lesion _n_ in case;
> if a positive case has more than one aneurysm lesion, then the content of "lesion_bbox.txt" will contain multi rows lesion records corresponding

Thanks for your explanation. That make sense.
And here may be the last question for this issue:
just wanna comfirm that are 'zxy' the coordinates for the bottom left  corner of the box, and 'dwh' the length in z, x, y direction?

**Comment by deepwise-code** [comment]
an example for crop aneurysm lesion region, image_zxy[z:z+d+1, x: x+w+1, y: y+h+1]



***@***.***
 
From: Yashi-Nan
Date: 2021-03-30 14:43
To: deepwise-code/DLIA
CC: deepwise-code; Comment
Subject: Re: [deepwise-code/DLIA] bbox info (#1)
one row info in "lesion_bbox.txt" file, these fileds mean:
0: patient id of positive anenurysm case, witch also can be found in train dataset
1-6: lesion bbox info with order zxydwh of lesion n in case;
if a positive case has more than one aneurysm lesion, then the content of "lesion_bbox.txt" will contain multi rows lesion records corresponding
Thanks for your explanation. That make sense.
And here may be the last question for this issue:
just wanna comfirm that are 'zxy' the coordinates for the bottom left corner of the box, and 'dwh' the length in z, x, y direction?

**Comment by Yashi-Nan** [comment]
Thanks a lot for your help!
I'll close this issue for now.

Yashi
