### ISSUE TITLE
Where is code for normalization preprocessing?

### ISSUE THREAD

**Issue by RylanSchaeffer** [deepwise-code/DLIA#10]
The Nature Communications paper has a paragraph that discusses brightness normalization preprocessing. I'm having trouble finding where in the code this is performed. These two lines suggest to me that only one window interval is used, not three:

https://github.com/deepwise-code/DLIA/blob/f85c5d8f824765996d3334b4e71f287f356ae98c/tasks/aneurysm/datasets/aneurysm_dataset.py#L30-L31

Can you please point me in the right direction?

I'm referring to the following paragraph in the paper:

<blockquote>
"In the inference stage (Fig. 1b), the segmentation prediction of the whole volume was generated by merging the prediction of uniformly sampled patches. Two adjacent patches may have 1/8 overlap, in other words, the strides along the three axes were all 40. For each voxel, we used the highest probability from all enclosing patches as its final prediction. In order to detect IAs in some low-contrast images clipped by the default window interval of [0, 900], another two intervals of [0, 450] and [−50, 650] were used to normalize the source images. The setting was automatically selected according to the brightness distribution. Given a bone-removal CTA image, a threshold value such as 150 Hu was used to find the initial area of vessels and then the maximum connectivity area was kept as the final region of vessels. Histogram of the brightness of voxels in the region was analyzed to find suitable clipping interval. We counted the distribution of three intervals including [0, 200], [200, 300], and [300, 500], which corresponded to clipping intervals of [0, 450], [−50, 650], and [0, 900], respectively. Finally, the clipping interval corresponding to the dominated distribution interval was selected to normalize the source images."
<blockquote>

Thank you for your help!

**Comment by deepwise-code** [comment]
With extract some features from cta image and ww wl info from doctor suggest,  we trained a traditional ml model to get a suitable result for preprossing image; Inaddition, wwwl(900,450) are suitable for almost datas in out datas.
