### ISSUE TITLE
Why the precision of the example so low?

### ISSUE THREAD

**Issue by YingJGuo** [deepwise-code/DLIA#14]
I ran the code "python main.py --gpu 0 --train --config tasks/configs/aneurysm_seg.daresunet.yaml " 
then train the example and val it 
But the metrics always only 
"lesion-level: precision=0.0001(1/6817),recall=1.0000(1/1)
person-level: Sensitivity=1.0000(1/1),Specificity=0.0000(0/0)"
Why so low ? Is that example right?
Or any wrong i used the code ?

**Comment by deepwise-code** [comment]
Run time is diffecnt by different hardware(eg cpu/gpu/ram..) and software (eg cuda+cudnn) environment. you can share yourself runtime environment for us to further problem analysis and suggestion. By the way in our vis_demo.ipynb, eval example data cose ~40s with sigle gpu 2080Ti and cpu E5-2697 v4 @ 2.30GHz

**Comment by YingJGuo** [comment]
whats,,, My hardware is single gpu TITAN_X and CUDA 11.2
But is that any connections between the low precision of the example and my hardware??

**Comment by deepwise-code** [comment]
Sorry for miss undertand.You mean you have tried to use one data of our support to train and evaluate it? And fp is very much?

**Comment by YingJGuo** [comment]
Yes, I used your data "example" and "example_mask"
then ran "python main.py --gpu 0 --train --config tasks/configs/aneurysm_seg.daresunet.yaml" to train 
But the eval fp is very much , tp nearly 0

**Comment by deepwise-code** [comment]
command ''python main.py --gpu 0 --train --config tasks/configs/aneurysm_seg.daresunet.yaml'  contains default parameters to check training pipline work well. It give a correct demo output template in training for checking new dataset format. In view of default configuration parameters don't specify pretrain model, suggest base yourself dataset and specify pretrain model to start your training.

**Comment by YingJGuo** [comment]
I tried the "--main.py --test" and the checkpoint to check if the training pipline work well. It actually worked not bad, even with a lot of fp, but it also has a lot of tp.
And here is my question:  why the test part can work well but the val part always shows low tp (like 1/2319).  The segmentation result seems not only 1 tp obviously. Is that any code i should change for val part? maybe the val part didn't use the lastest checkpoint?
thanks for your help

**Comment by YingJGuo** [comment]
Another quesiton about the bbox: what the bbox should be set if the aneurysm is not only one?
for example, the data has 3 IAs.
Should it like 
"example 2 3 4 10 10 10
example 7 20 11 10 10 10
example 30 21 18 10 10 10 "
or I can only make a big bbox which contains them all ?

**Comment by YingJGuo** [comment]
> Another quesiton about the bbox: what the bbox should be set if the aneurysm is not only one? for example, the data has 3 IAs. Should it like "example 2 3 4 10 10 10 example 7 20 11 10 10 10 example 30 21 18 10 10 10 " or I can only make a big bbox which contains them all ?

This question has been solved
