### ISSUE TITLE
How was Test / Inference Threshold of 0.3 Chosen?

### ISSUE THREAD

**Issue by RylanSchaeffer** [deepwise-code/DLIA#8]
In the aneurysm segmentation test function, there's a threshold value of 0.3:

https://github.com/deepwise-code/DLIA/blob/f85c5d8f824765996d3334b4e71f287f356ae98c/tasks/aneurysm/aneurysm_seg.py#L208

How was this value chosen?

**Comment by deepwise-code** [comment]
this is empirical probability threshold according out segmetation matrix statistic
