### ISSUE TITLE
example image inference is not working on test

### ISSUE THREAD

**Issue by wshi8** [deepwise-code/DLIA#9]
I tried to run "test" on the example image you provided and used the weights you provided. The predicted seg is all blank (black) even though it has aneurysm. Any suggestion? is there any better data/image that can be used to test the model? How do we know the model is working?

**Comment by deepwise-code** [comment]
with vis.demo.ipynb script, you can get expect segementation visualization results of lesion slices, same as files in the directory: raws/vis/example
